### ISSUE TITLE
Permission denied while building

### ISSUE THREAD

**Issue by Ledge2494** [sa-shiro/Satisfactory-Dedicated-Server-ARM64-Docker#1]
Hello,

Description:
I got a permission denied while running `build.sh` on step 10/13 when it comes to download and run steamcmd on new user `steam`

Step to reproduce :
clone git repo
run `sh build.sh`

Configuration :
Oracle Cloud ARM based processor running ubuntu 22.04

Output (in no cache):
```
STEP 8/13: USER steam
--> 9bfffe96d32
STEP 9/13: WORKDIR /home/steam/Steam
--> 69dbc5bbbfd
STEP 10/13: RUN curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
steamcmd.sh
tar: steamcmd.sh: Cannot openlinux32/steamcmd
: Permission denied
tar: linux32: Cannot mkdir: Permission denied
linux32/steamerrorreporter
tar: linux32/steamcmd: Cannot open: No such file or directory
tar: linux32: Cannot mkdir: Permission denied
tar: linux32/steamerrorreporter: Cannot open: No such file or directory
linux32/libstdc++.so.6
tar: linux32: Cannot mkdir: Permission denied
linux32/crashhandler.so
tar: linux32/libstdc++.so.6: Cannot open: No such file or directory
tar: linux32: Cannot mkdir: Permission denied
tar: linux32/crashhandler.so: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors
Error: error building at STEP "RUN curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -": error while running runtime: exit status 2
```

**Comment by sa-shiro** [comment]
Trying to reproduce your issue, you've run `build.sh` and `build-nocache.sh` right?
Did you install docker correctly?
Did you set up IPv6 on your Oracle Instance? (this can cause a lot of issues)

as of my tests running `build-nocache.sh`:

![image](https://github.com/sa-shiro/Satisfactory-Dedicated-Server-ARM64-Docker/assets/7215049/7ca59dde-e45d-4f21-ae72-b7cb9ce31606)

My advice is to completely purge the docker cache:
```
sudo docker compose down (just in case it might be running somehow)
sudo docker image rm satisfactory-arm64
sudo docker ps -a (displays all containers and the image they are using)
sudo docker container rm [CONTAINER] (remove any satisfactory related container)
sudo docker image rm [CONTAINER_IMAGE]
sudo docker builder prune -a (this will remove all build caches)
```

If this still doesnt work, try removing and re-installing docker by following this tutorial:
[Install Docker Engine on Ubuntu](https://docs.docker.com/engine/install/ubuntu/)

Also please keep in mind that currently running a dedicated server on  linux seem to be broken, see:
- (Reddit) [[Dedicated Server] Everytime I try to put conveyor belts server crashes](https://www.reddit.com/r/SatisfactoryGame/comments/187py9k/dedicated_server_everytime_i_try_to_put_conveyor/)
- (Satisfactory Q&A) [UPDATE 8 - UOBJECT MAX LIMIT CRASHES INCREASING - Early Access: 264901](https://questions.satisfactorygame.com/post/65613ca4d0053b102f18f4c2)

**Comment by Ledge2494** [comment]
Thanks for your help, it was just a bad docker installation (I was using the wrong package), changing that fix the whole installation process

**Comment by sa-shiro** [comment]
no problem :)
