### ISSUE TITLE
Running the server outside of a Docker Container using FEXEmu and SteamCMD does not fix the crashing issue

### ISSUE THREAD

**Issue by Balouxe** [sa-shiro/Satisfactory-Dedicated-Server-ARM64-Docker#2]
Not an issue but didn't know where else to say this, running the server outside of a Docker Container using FEXEmu and SteamCMD does not fix the crashing issue.

**Comment by sa-shiro** [comment]
We have to wait until 1.0 to see if it got fixed, its unlikely they push a dedicated server update anytime soon before 1.0 :(

**Comment by Balouxe** [comment]
Yup :'(
