### ISSUE TITLE
Conveyor Belt Crash Fix?

### ISSUE THREAD

**Issue by Pixelzated** [sa-shiro/Satisfactory-Dedicated-Server-ARM64-Docker#6]
Is there any possible way to have this problem fixed now that 1.0 is out?

**Comment by sa-shiro** [comment]
As stated in the readme there is currently no way to fix this issue.

The server basically only functions as a kind of middleman: one of your friends or yourself downloads the save and reuploads once you're done playing.

That way your friends don't have to rely and wait for someone to host the multiplayer session and can play any time they want (they just have to make sure to reupload the save to the server).

ARM is an unsupported platform, but with the announcement of a console release we might get some love for the ARM platform!

**Comment by Pixelzated** [comment]
Ok
