### ISSUE TITLE
CMake Error (Qt5)

### ISSUE THREAD

**Issue by pascui** [sa-shiro/Satisfactory-Dedicated-Server-ARM64-Docker#7]
Hello,

Description:
I get an error at step 13/23 while running build.sh.
CMake trys to find a package configuration file provided by "Qt5", but can't find it.

Step to reproduce :
clone git repo
run sh build.sh

Configuration :
Oracle Cloud ARM based processor running ubuntu 22.04

Output:
```
=> ERROR [13/23] RUN CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX=/
CMake Error at Source/Tools/CMakeLists.txt:7 (find_package):
By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Qt5", but
CMake did not find one.

Could not find a package configuration file provided by "Qt5" with any of
the following names:

Qt5Config.cmake
qt5-config.cmake

Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
to a directory containing one of the above files.  If "Qt5" provides a
separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/FEX/Build/CMakeFiles/CMakeOutput.log".
See also "/FEX/Build/CMakeFiles/CMakeError.log".
```

**Comment by RisedSky** [comment]
Try my repo and tell me if it's fine with that.

https://github.com/RisedSky/satisfactory-arm64-docker

**Comment by sa-shiro** [comment]
weird, im unable to reproduce the issue - fresh oci instance as well

**Comment by ArthurMTX** [comment]
I added 
```
RUN apt-get update && apt-get install -y \
    qtbase5-dev \
    qttools5-dev \
    qttools5-dev-tools \
    qtdeclarative5-dev
```

And it works perfectly.
![image](https://github.com/user-attachments/assets/e2144513-38f7-4560-bed3-bf2c902a82d4)

**Comment by pascui** [comment]
> I added
> 
> ```
> RUN apt-get update && apt-get install -y \
>     qtbase5-dev \
>     qttools5-dev \
>     qttools5-dev-tools \
>     qtdeclarative5-dev
> ```
> 
> And it works perfectly. ![image](https://private-user-images.githubusercontent.com/78091139/369191544-e2144513-38f7-4560-bed3-bf2c902a82d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzQ4ODgsIm5iZiI6MTcyNjgzNDU4OCwicGF0aCI6Ii83ODA5MTEzOS8zNjkxOTE1NDQtZTIxNDQ1MTMtMzhmNy00NTYwLWJlZDMtYmYyYzkwMmE4MmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEyMTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZjlmYzBmMDI1ZGI2MzdmYWM0NjBhMWEzN2QzNDRiM2Y3NGFlNjU1YmNhNWVmMGVmM2VjY2Q1MDZjNzZjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K8IvpLzAGHq9-NYsht6JK0xg9CoM8sDSFAvOqkvoX8A)

This fixed it. Tyvm!
